### ISSUE TITLE
Add shorthand inheritance syntax for specifying template

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-view#10]
Most `Dry::View::Layout` subclasses only configure their template name, and nothing else. It would be handy to add a shorthand for this, e.g.

``` ruby
class MyView < MyApp::View["foo/bar"]
end
```

where `"foo/bar"` is the template name.

**Comment by timriley** [comment]
Open thinking about this further, I'm not sure this is something worth building into dry-view itself. Shortcut template declarations, or even inferring of template names, is something that can be done when dry-view is incorporated into an app. This feels like the better place for it since it can take the app's own conventions into account.

**Comment by solnic** [comment]
I agree. dry-view should remain relatively simple. Automation (including generating view classes automatically when a template exist w/o an explicit view class) can be done separately. A good analogy are rom-rb's commands. You can define them explicitly, and for common cases it's a PITA, but then we have repos that define these commands for you automatically for common cases, yet it's always possible to define your own command class and handle less common, complex cases yourself.
