### ISSUE TITLE
stack level too deep (SystemStackError) when using layout

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-view#128]
Steps to reproduce:

  1. Clone locally `hanami` (`enhancement/container-actions-views` branch, at `95a194a`)
  1. From the Hanami codebase find: `Hanami::Loaders::View#configure`, uncomment the `layout` line
  1. Clone locally Soundeck (https://github.com/jodosha/soundeck.git, `feature/views` branch, at `f5d70fd`)
  1. Make Soundeck `Gemfile` to point to local `hanami` gem
  1. Start the server for Soundeck app (`bundle exec hanami server`)
  1. Visit http://localhost:2300/
  1. The app crashes

**Comment by jodosha** [comment]
I mistakenly placed the layout at `apps/web/templates/application.html.erb`, but it should've been placed at `apps/web/templates/layouts/application.html.erb` instead.

A few considerations:

  * `SystemStackError` is still a symptom of something really wrong happening
  * We should raise a meaningful error message. e.g. `cannot find layout apps/web/templates/layouts/application.html.erb`
  * The convention of using `layouts` can potentially clash with templates that want to use that namespace (e.g. `layouts/index` for `Layouts::Index` in a dev application)
  * By moving the file in the expected place the layout isn't rendered. I can open another ticket for this.

**Comment by jodosha** [comment]
I ran into other cases where this problem happens:

  1. If I create the view, but I forget to create the template, it crashes. Please note that per Hanami conventions, the template name is assigned automatically at the boot of the app.
  1. If I assign a template with `config.template = "albums/new"`. It could be possible that this is related to case 1: it fails to find the template and it crashes.

**Comment by timriley** [comment]
@jodosha Thanks for all the info here. I've done some debugging today, which has helped me figure out how to prevent the `SystemStackError`, as well as some other improvements to tighten up the behaviour in general around path handling and template lookup.

One question for you at this point. You mentioned:

> The convention of using `layouts` can potentially clash with templates that want to use that namespace (e.g. `layouts/index` for `Layouts::Index` in a dev application)

Do you see this being an actual issue? In setting it up this way I was just following the Rails-established convention of layout handling.

Perhaps a smarter default for `layouts_dir` would be `nil`, with layouts just being looked up from the root of the known paths? Then, as a user of dry-view, if you do want to use a certain dir for layouts, you can populate the `layouts_dir` setting yourself, or simply specify the layout name in full, e.g. `layout = "layouts/application"`. What do you think?

**Comment by jodosha** [comment]
@timriley Thanks for having a look at this.

Layouts: It was a comment regarding my expectation, and an explanation of why Hanami has layouts under `apps/*/templates`. It wasn't a request to change the behavior of `dry-view`. 😉

**Comment by timriley** [comment]
@jodosha apart from solving this, I've also done a round of tightening up the template lookup and config handling, which you can see in https://github.com/dry-rb/dry-view/pull/130
