### ISSUE TITLE
Template isn't reloaded until rack app is restarted.

### ISSUE THREAD

**Issue by graudeejs** [dry-rb/dry-view#134]
Hello!

I'm trying to use dry-view in my latest project. It works find, however there is one inconvenience.
While I'm developing after I modify template I need to restart rack app in order to have view output updated (First render is fine, subsequent renders would use cached template instead of reparse updated template).

It would be cool if there was either setting to parse template on each request, or a method that could be called or something.

Is this is expected behavior?

EDIT:
At first I was thinking that it might be some weird hamlit issue, but I could reproduce same behavior with slim

EDIT 2:
For now I swapped dry-view to hanami-view since I'm just starting out (plus to see if the problem is not related, how I set up my app). with hanami-view I don't have this issue. Would still prefer to find a way to use dry-view.

**Comment by waiting-for-dev** [comment]
Probably this is about the configuration of your code reloading mechanism and has nothing to do with dry-view. Have you added haml and slim file extensions to it?

**Comment by graudeejs** [comment]
Hello!
I do have file extensions `.html.slim` or `.html.haml` depending on used engine.

I've created small repo that can be used to reproduce this issue: https://github.com/graudeejs/dry-view-issue-134-code

**Comment by solnic** [comment]
this is not an issue with dry-view, something like code reloading must be handled either by you or a framework that you use. you can simply reload the server whenever a file is changed. I use `entr` for that, but there are also ruby solutions likes `guard` or `shotgun`.

**Comment by graudeejs** [comment]
But I am reloading code. Is there any specific stuff that I need to be able to reload views (or more precisely templates)?

**Comment by graudeejs** [comment]
So, to work this around, had to create `Dry::View.reset_cache!` method
```
  require 'dry/view'
  require 'dry/view/renderer'
  require 'dry/view/path'
  require 'dry/view/scope_builder'
  require 'dry/view/part_builder'
  module Dry
    class View
      def self.reset_cache!
        [self, Renderer, Path, ScopeBuilder, PartBuilder].each do |klass|
          klass.instance_variable_set(:@__cache__, ::Concurrent::Map.new)
        end
        nil
      end
    end
  end
```
Technically it seems enough to just reset cache of `Dry::View::Renderer`, however for correctness of environment after reload I decided to reset all of it (Might change that in future)

**Comment by solnic** [comment]
@graudeejs yep, this is what's required to make things work. In the future we'll have a more unified caching mechanism across all the gems, so resetting caches will be very simple. I also plan to start dry-rails project that would provide support for reloading OOTB (amongst other things).
