### ISSUE TITLE
Make definition of locals nicer

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-view#14]
Right now, most of a view's logic sits inside a single `#locals` method where it returns the hash of locals it wants passed to the template. This is not very nice, and leads to a lot of [awkward methods like this](https://github.com/icelab/berg/blob/ef430f4c5dcfc26c23a6616dcb128b00ef46135b/apps/main/lib/main/views/posts/index.rb#L16-L26).

It'd be better if we could have each of our view's locals provided via a dedicated method that is marked as a local or an "exposed" method, so instead of this:

```ruby
def locals(options)
  # setup stuff here
  
  super.merge(
    foo: something,
    bar: something_else,
  )
end
```

we have something like this:

```ruby
local def foo
  something
end

local def bar
  something_else
end
```

Where `local` or maybe `expose` is a class-level macro that accepts a method name (e.g. `local :foo`, like in that example above) and then makes it part of the set of locals passed to the template.

The tricky thing here is that our view instances here are long-lived, with all the per-request data coming into `#call` only, so that data can't really sit on the instance and be available for instance methods to play with. We might be able to do some trickery to make it _look_ like this though 😏

**Comment by timriley** [comment]
Revisited this for a think. I think that doing some trickery to try lift methods out of one context and plant them into another won't ever be intuitive. It'll more likely confuse than help.

So I think perhaps something like this might be better:

```ruby
module Main
  module Views
    module Posts
      class Index < Main::ViewController
        include Main::Import["persistence.repositories.posts"]

        configure do |config|
          config.template = "posts/index"
        end

        prepare do |input|
          posts = controller.posts.listing(
            controller.posts.listing(
              page: input.page,
              per_page: input.per_page
            )
          )

          expose :posts, Decorators::PublicPost.decorate(posts)

          expose :indexed_posts, posts.map.with_index { |post, i|
            OpenStruct.new(index: i, post: post)
          }

          expose :paginator, posts.pager
        end
      end
    end
  end
end
```

So, instead of `#locals` where you munge the input and return a hash, have a class-level `.prepare` block that is executed with the input, and provides a helper like `#expose` to allow the class author to pass locals to the view one by one, and have a bit more space to set things up nicely.

(Underneath, this would all be a nicer API on top of something similar to what is happening now in terms of preparing a hash of locals. Class authors could always just go ahead and build custom `#call` or `#locals` methods directly if they wanted).

Thoughts?

**Comment by solnic** [comment]
How about:

``` ruby
class ViewController
  def call(input)
    view_locals = self.class.exposures.each_with_object({}) do |(name, blk), h|
      h[name] = blk ? instance_exec(input, &block) : __send__(name, input)
    end
    # the reset of stuff
  end

  def self.expose(name, &block)
    exposures << [name, block]
  end

  def self.exposures
    @exposures ||= []
  end
end

class Index < ViewController
  expose :posts
  # slightly trickier but totally doable (we can look at block arg names and
  # if they match other exposures then we tsort them by deps and execute in
  # the right order to get arguments for other exposures, like "posts" here)
  expose :paginator { |posts| posts.pager }

  def posts(input)
    # do stuff to return posts
  end
end
```

This way you can either use inline blocks or method names, and we can easily aggregate all the needed locals using isolated methods/blocks, no need for a nested DSL.
WDYT?

**Comment by timriley** [comment]
@solnic this looks very nice! And a little closer to what I was thinking about in the first place.

My only concern would be making it possible for exposure blocks/methods to access common things that you _don't_ want to expose, e.g. the equivalent of this:

```ruby
def locals(options)
  shared_thing = do_something_with(options[:foo])

  {
    one: prepare_for_view(shared_thing)
    two: more_stuff_happening_to(shared_thing)
  }
end
```

Perhaps we need another keyword besides `expose` that does everything else _apart_ from including it in the view's locals?

**Comment by solnic** [comment]
@timriley views are not singletons so we can use their state to share common stuff between exposure methods, wdyt?

**Comment by timriley** [comment]
@solnic I dunno, that doesn't seem right? Since they're not meant to carry state from one `#call` invocation to another?

**Comment by timriley** [comment]
That said, if we're sharing objects (private or otherwise) between exposures, it'd make sense to capture/memoize them somehow, because otherwise we'd be wasting cycles in rebuilding them for each usage. This was part of the motivation in putting together that other `.prepare` block example, since it makes it clear we only set up that `posts` object once.

**Comment by solnic** [comment]
@timriley yeah they must be be memoized, I *think* we can avoid any `prepare` blocks, it would be good to keep these objects relatively simple
