### ISSUE TITLE
part configuration

### ISSUE THREAD

**Issue by dsisnero** [dry-rb/dry-view#148]
## should be able to configure part dirctory

When I use part the documentation doesn't show where the parts folder should live or how to configure parts

add the ability to configure parts directory and add a default search path

**Comment by timriley** [comment]
dry-view doesn't have any opinion about where and how you define your part classes. All it does is attempt to find the class constants by name, and if it can't, it falls back to the base part class.

See `PartBuilder#resolve_part_class` for details. This is already set up to work nicely with class autoloaders, too.

As such, there's no need for a "search path" to be configured for parts. It's the application author's job to make sure the part classes are already available by the time the view is called.

To make this clearer, I've added this note to the documentation: https://github.com/dry-rb/dry-view/commit/201d522458c55c7911d6fc762c66085478f20fad

Thanks for your report! I'd be happy to further clarify this aspect of dry-view and more, but I think the best place to do this is in the dry-rb forums: https://discourse.dry-rb.org
