### ISSUE TITLE
Make scope available everywhere

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-view#15]
I think this might be helpful:

Just make it so the "scope" on a `Dry::View::Layout` is available on _every_ template rendered from it. This would make e.g. providing a CSRF token (which has to come from the "outside world") to _all_ the templates that get rendered in a view (both the top-level template and any constituent partials) much simpler.

This is a bit more coupling of the view object to the templates, but I think the extra convenience would make up for it. And we could make it clear that this is only intended for a few truly "global" or "environmental" things. It might fit also nicely if we're renaming `Layout` to `ViewController` too (#12).

**Comment by timriley** [comment]
Another thing to consider here is whether "scope" is the best name for this thing.

**Comment by solnic** [comment]
Maybe we could just provide a bunch of common things to all the views, instead of the whole layout scope? (just thinking out loud)

**Comment by timriley** [comment]
Yeah, I can see the benefit of keeping the layout's particular scope separate from the common "context" that you want set up for all views.

**Comment by timriley** [comment]
Fixed by #26
