### ISSUE TITLE
Add `Part#new`

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-view#53]
I just stumbled upon a use case where I wanted to recursively render a template via a part, based on "changing" `value`, I ended up implementing `Part#new` to simplify this:

``` ruby
def new(pages)
  self.class.new(name: _name, value: pages, renderer: _renderer)
end
```

So how about we just add it to dry-view, because I'm 100% sure it'll be useful in many cases?

**Comment by timriley** [comment]
Related, [my similar implementation](https://github.com/icelab/icy-form/blob/a7ac09760a8bd161d8bd302322a0eba1a2244212/lib/icy/form/view/part.rb#L9-L17) in icy-form's base Part class:

```ruby
def new(klass = (self.class), name: (_name), value: (_value), **options)
  klass.new(
    name: name,
    value: value,
    context: _context,
    renderer: _renderer,
    **options,
  )
end
```

I wanted this one to be particularly flexible, and even allow creating an instance of a different part class  while passing along the current context/renderer.

@solnic reckon that implementation would be fine to pull in?

**Comment by solnic** [comment]
@timriley totally
