### ISSUE TITLE
Entity attributes not being called properly with manual initialisation

### ISSUE THREAD

**Issue by makenosound** [dry-rb/dry-view#61]
Having an issue where the underlying attributes of an entity passed to a view part seem to not be available as methods like I’d expect.

I’m initialisating this directly on a `View::Context` object as I want them available across the app:

```ruby
# auto_register: false

require "foo/view/context"
require "main/view/parts/thingie"
require "main/import"

module Main
  module View
    class Context < Foo::View::Context
      include Import[
        "thing_repo"
      ]

      def things
        thing_repo.listing.map { |thing|
          Main::View::Parts::Thing.new(
            name: :thing,
            value: thing,
            context: self
          )
        }
      end
```

Here’s the corresponding view part:

```rb
# auto_register: false

require "main/view/part"

module Main
  module View
    module Parts
      class Thingie < Main::View::Part
      end
    end
  end
end
```

Calling `thingie.name` in the template results in:

```
undefined method `name' for #<Main::View::Parts::Thingie:0x00007f7f9941b048> Did you mean? _name
```

Accessing the value directly in the view part is fine:

```ruby
def name
  _value[:name]
end
```

**Comment by timriley** [comment]
@makenosound This appears to be fixed with the latest dry-view changes, which among other things, supports properly decorating values returned from context objects.
