### ISSUE TITLE
Reconsider terminology

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-view#65]
Here's what we have now.

Core, user-facing concepts:

- **Controller** — the main entry point to a view
- **Template** — holds the view's contents, configured per-controller
- **Partial** — a template fragment intended for re-use from loops or multiple templates
- **Format** — a specific representation of a view, via a named template. Allows a a single view to be rendered in different ways, via differing template extensions (e.g. `index.html.slim` and `index.json.yajl`). Multi-format support is provided in whole by Tilt.
- **Exposure** — defined within each controller, determines one of the values that are made available to the template. Exposures can have **exposure dependencies** too, where one exposure has access to the value from another.
- **Part** — wraps the value returned from an exposure, has access to rendering-related facilities. Parts can come as custom subclasses providing view-specific behaviour around different values.
- **Scope** — the rendering context for a template (i.e. the template's `self`). Holds the **locals** (the parts returned from the exposures), the context, and other rendering-related facilities. Scopes can come as subclasses providing behaviour intended for specific templates or partials.
- **Context** — an object whose methods are made available to all templates via the scope. This makes it "global",  the baseline environment for an entire rendering (for both templates and parts).

Supporting concepts:

- **Part builder** — configurable object that determines the part class to use when wrapping exposure values. A framework like Hanami might provide its own scope builder when integrating dry-view.
- **Part namespace** — a configurable module used by part builders to determine how part classes are looked up
- **Scope builder** — configurable object that determines the scope class to use when preparing scopes. A framework like Hanami might provide its own scope builder when integrating dry-view.
- **Scope namespace** — a configurable module used by scope builders to determine how scope classes are looked up
- **Tilt adapter** — low-level shim that ensures a compatible template engine is used when rendering templates in particular languages (right now, `erb` and `haml`).

**Comment by timriley** [comment]
@jodosha @AlfonsoUceda here's a run through of our current terminology for you.

The most unusual of these, as you've noted, are "controller" and "part".

I feel "controller" is actually appropriate since its job is to coordinate multiple parts of the application to prepare the data for the template. It's not really the "view" on its own, since the "view" is the combined effect of a controller and the rendering of its templates (even though within an application development context I do tend to refer to the controller classes as "views").

As for "part", I suppose you could replace it with "presenter" or "decorator", but I feel the difference in terminology here is actually helpful, as a hint that parts operate a little differently to what we've seen branded as presenters or decorators elsewhere in the Ruby ecosystem (i.e. parts have access to almost the entirety of the view rendering environment, which is part of the key value proposition for dry-view).

The other thing I like about the term "part" is how well it fits with its neighbouring concepts: part, scope, context. They're all very strongly noun-like terms, which is appropriate, since these objects are all initialized with values as state. On the other side, we have the more verb-made-noun terms, like controller, part builder, scope builder, which are functional objects, initialized with config only, with the values passing through `#call`. I know this is a subtle differentiation, but I made it consciously, and I do think it helps.

Anyway, if we want to tweak any naming, now is the time. Happy to continue the discussion here or elsewhere.

**Comment by jodosha** [comment]
@timriley Thanks for putting this together. This glossary will be extremely useful both internally and for final devs (guides).

I agree to having _part_ to differentiate "take the distance" from concepts like _presenters_ and _decorators_, but I don't think it's the case for _controller_. IMO that is a _view_, and should be named so.

Also, having _controller_ as term in view layer (as V of MVC), it's counter-intuitive.

**Comment by timriley** [comment]
Thanks for your feedback, @jodosha :)

After thinking it through some more, I think a rename of `Controller` to something else would indeed be beneficial to this project and users’ understanding of it.

Like you indicated, the most obvious renaming would be `Dry::View::Controller` => `Dry::View`, but we're taking a moment just to see if we can think of any alternatives.

Do you have any other ideas?

**Comment by waiting-for-dev** [comment]
Does it sound too ugly `Dry::View::View`? `Dry::View` is the namespace, and within there you have the `View`.

A middle way could be `Dry::View::ViewController`, but I also prefer just `View` for the `MVC` influences.

**Comment by solnic** [comment]
> Does it sound too ugly `Dry::View::View`?

Yes this would be horrible 😆

**Comment by timriley** [comment]
I'm going to make it `Dry::View`.

**Comment by waiting-for-dev** [comment]
> > Does it sound too ugly `Dry::View::View`?
> 
> Yes this would be horrible

Hahaha... well, I disagree :smile:
