### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-view#94]
Our benchmark shows that dry-view is ~2.5x slower (in this specific benchmark at least) than ActionView. After quick profiling, you can see that `template?` is extremely expensive:

![dry-view-profile](https://user-images.githubusercontent.com/1066/50287278-76537d80-0462-11e9-99e4-3baf280f927d.png)

**Comment by solnic** [comment]
@GustavoCaso re graph - I use `hotch` gem https://github.com/splattael/hotch

**Comment by GustavoCaso** [comment]
@solnic Thank you so much. I did not know that tool existed  🎉

**Comment by GustavoCaso** [comment]
This issue has been addressed by https://github.com/dry-rb/dry-view/pull/97
